spring.application.name=api-gateway
server.port=8080

# Gateway Routes

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# EMPLOYEE SERVICE
spring.cloud.gateway.routes[1].id=employee-service
spring.cloud.gateway.routes[1].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/employees/**

#file-service
spring.cloud.gateway.routes[2].id=file-service
spring.cloud.gateway.routes[2].uri=lb://FILE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/files/**

#analytics- service
spring.cloud.gateway.routes[3].id=analytics-service
spring.cloud.gateway.routes[3].uri=lb://ANALYTICS-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/analytics/**

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost