
spring.application.name=FILE-SERVICE

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# FILE SIZE

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

eureka.instance.hostname=localhost

eureka.instance.prefer-ip-address=true